### ISSUE TITLE
Gun is not visible when obtained as a quest reward

### ISSUE THREAD

**Issue by Dwismas** [wuergrob/DOS2_Mod_Musketeer#1]
When I became champion of the Driftwood Arena, I selected a gun as a reward. When I went to equip it, it did not appear in my inventory. In fact, when I unequipped the gun I was currently using, the reward gun's stats are applied and I can even use the weapon. The weapon slot is still shown as unarmed.

**Comment by Dwismas** [comment]
Also, as a side note. How much damage is one expected to throw out there? The reward gun is marked to deal about 90 damage baseline. With me as a lone wolf character, I have it slightly min-maxed so I deal about 500 damage with all the multipliers in effect per shot. It seems a little high at my level.

**Comment by wuergrob** [comment]
![DOS2_Musketeer_EmptyQuestReward](https://user-images.githubusercontent.com/32273110/100542539-c9d3c600-324a-11eb-85a9-d858ac514ca8.png)

I've managed to replicate this issue by completing the Driftwood Arena Quest a few times. @Dwismas can you confirm that this is the same kind of issue you encountered?

Are you also running the LeaderLib mod and the WeaponExpansion Mod from Laughing Leader? This issue might be related to one of those mods.

**Comment by Dwismas** [comment]
@wuergrob It is not quite the same. The icon of the weapon was there when I selected the quest rewards, but when I received them, it did not look like it was there. When I had no weapons equipped, the reward weapon's stats were applied. When hovering over other weapons in my inventory, the reward weapon's information shows up for comparison like normal. When I equip some other weapon, the reward weapon is nowhere in my inventory to be found, but I can just unequip the current weapon to use it.

**Comment by wuergrob** [comment]
Thanks for clarifying. Are you running LeaderLib and/or WeaponExpansion? Or a mod that does something with quest rewards specifically? My mod does not change quest rewards directly, so I'm unsure whether this is caused by a interaction with another mod or not.

**Comment by Dwismas** [comment]
I will make sure that the required stuff is running, but I am pretty sure that my friend (the host) had them applied. We avoided using any other mod for this run and pretty much only used this mod, it's required things, and the gift bags.

**Comment by wuergrob** [comment]
Would be great if you could ask your friend about LeaderLib and WeaponEx specifically, as I think WeaponEx adds additional weapon types to quest rewards. I'll keep looking into it, but hope it's still playable for you until it's fixed.

**Comment by Dwismas** [comment]
Yeah. I can still use it. Even the ammo ui works for the ghost gun. Only thing is that the damage seems a little imbalanced to me.

**Comment by wuergrob** [comment]
I agree that the damage values are on the high side at the moment. Base damage for weapons and some skills will be reduced by quite a bit, whilst upping some of the "Marked" interaction effects. If there are specific things that bother you, then feel free to leave a comment about those as well, I'm always open for feedback.

**Comment by wuergrob** [comment]
It appears, that this issue is caused by a issue in Laughing Leader's Weapon Expansion mod. I think he has temporarily disabled a feature that caused this, so if you keep encountering this problem, make sure to let me know. If you can provide additional details as well, such as a screenshot and a modlist or a savegame, then that would also be appreciated.
